# Generated by Django 4.1.6 on 2023-02-14 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('content', models.TextField(verbose_name='Зміст')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateField(auto_now=True, verbose_name='Оновлено')),
                ('rubric', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='posts.headings')),
            ],
            options={
                'verbose_name_plural': 'Дописи',
            },
        ),
    ]
